[package]
name = "classic-indev-converter"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.9"
toml = "0.8.22"
serde = { version = "1.0.219", features = ["derive"] }
rusqlite = "0.35.0"

mc-classic = "0.1.0"

